### ISSUE TITLE
Empty strings as nulls?

### ISSUE THREAD

**Issue by ujovlado** [keboola/fakturoid-writer#1]
> Čau.
> 
> Prosím tě, když potřebuju do fakturoidu poslat u některých hodnot null, tak to v tabulce, kterou dám do writeru, má být jako string? Tedy např.: 'null' AS  "sent_at"?
> http://docs.fakturoid.apiary.io/#reference/invoices/detail-faktury
> 
> Díky,
> Matějkys

**Comment by ujovlado** [comment]
cc: @matejkys

**Comment by ujovlado** [comment]
@matejkys predpokladam, ze to chces poslat na jeden raz a u niektorych to mat ako null a u inych vyplnene?

**Comment by Matejkys** [comment]
@ujovlado teď nutně nemusím řešit, jestli to bude u jednoho řádku tak a u jiného jinak. ale například netuším, jaká bude url faktury. já teď nevím, jestli do toho sloupce mám dát všude prázdný string, nebo tam napsat 'null', nebo to je jedno

**Comment by Matejkys** [comment]
@ujovlado teď jsem dostal při zápisu hlášku, že to nemůže najít invoices.json.
Může to být tím, že tam neexistuje ještě žádná faktura?
ExceptionId docker-e408bb2f48322ef99b4f3719e4f3a2cc

**Comment by ujovlado** [comment]
K tej url faktury:
Jedina required polozka fakturoidu (ku fakture) je `subject_id`, ostatne tam vobec nemusis posielat. Url faktury potom zistis z tabulky, do ktorej writer uklada cele responses.

Napr. tabulka `in.c-keboola-fakturoid-writer-255573875.fakturoid-invoice`, ktora ma jediny stlpec, `data`, v ktorom je json:

```json
{
"id":3754816,
"url":"https://app.fakturoid.cz/api/v2/accounts/keboola/invoices/3754816.json",
"created_at":"2017-04-10T23:06:21.469+02:00",
"...": "..."
}
```

**Comment by ujovlado** [comment]
@Matejkys nie, nie je to tym ... posielas tam fieldy, ktore sa nemaju posielat :) ... `id`, `token` a pod. ... vyskusal by som to, byt tebou, najskor len so `subject_id`

**Comment by ujovlado** [comment]
A toto este kukni: https://github.com/keboola/fakturoid-writer#input

**Comment by ujovlado** [comment]
^to je minimal setup, ostatne fieldy dogeneruje fakturoid a ty potom len popridavas dalsie

**Comment by ujovlado** [comment]
No a k tym fieldom:
- ked tam das `NULL` (v DB), do csv to pride ako `""`, cize na API sa posle prazdny string `""` ( req. body `{"field": ""}` )
- ked tam nas `"null"` (v db)  v csv bude `"null"` a na api pojde `"null"` (req. body `{"field": "null"}` )

... je to proste CSV

**Comment by Matejkys** [comment]
Teď dostávám zase, že client_name je povinná položka, a že mám neexistující subject_id (to je ale blbost, páč jsem to odtamtud stáhnul).
ExceptionId docker-39c68d71d870dc1456ba7b4dd4546152

**Comment by ujovlado** [comment]
@Matejkys nebude to blbost, nejake FA to zalozilo ... ten `subject_id` tam asi fakt neexistuje

**Comment by ujovlado** [comment]
co je naprd, ze to vdaka tomu skoncilo chybou napriek tomu, ze zalozilo niekolko FA ... to fixne,

**Comment by ujovlado** [comment]
No longer needed
